
Create table tblClosedAgreements(
AgreementNo nvarchar(50) primary key,
Remarks nvarchar(200),
EntryBy nvarchar(50) default 'dsamaddar',
EntryDate datetime default getdate()
);

GO

Create proc spInsertClosedAgreements
@AgreementNo nvarchar(50),
@Remarks nvarchar(200),
@EntryBy nvarchar(50)
as
begin

	if exists(
	Select * from dbo.Agreement_Bondman Where AgreementNo=@AgreementNo
	)
	begin
		Insert into tblClosedAgreements(AgreementNo,Remarks,EntryBy)
		Values(@AgreementNo,@Remarks,@EntryBy)
	end
	else
		Print 'Agreement Not Exists.'

	
end
-- exec spInsertClosedAgreements '03/6303','Pre-Encash','dsamaddar'

GO

Create proc spGetClosedAgreements
as
begin
	Select * from tblClosedAgreements
end

GO

/*Run Scripts*/

exec spInsertClosedAgreements '01/10546','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10546','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10546','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10546','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10546','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6332','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6332','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6332','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6332','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6332','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6332','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6332','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6332','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6332','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6332','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6395','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6395','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6395','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6395','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6395','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6395','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6395','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6395','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6395','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6395','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6395','Under Loan','dsamaddar'
exec spInsertClosedAgreements '05/0564','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0564','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0564','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0564','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0564','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0568','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0568','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0568','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0568','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0568','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0568','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0568','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0568','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0568','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/3716-R1','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/3716-R1','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/3716-R1','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/3716-R1','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/3716-R1','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/3716-R1','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/3716-R1','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/3716-R1','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6399','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6399','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6399','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6399','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6399','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6399','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6399','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6399','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6399','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6399','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6399','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6399','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6400','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6400','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6400','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6400','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6400','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6400','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6400','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6400','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6400','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6400','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6400','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6400','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6401','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6401','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6401','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6401','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6401','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6401','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6401','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6401','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6401','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6401','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6401','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6401','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6415','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6415','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6415','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6446','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6446','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6446','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6446','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6446','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6446','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6446','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6446','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6446','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6446','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6483','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/6483','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/6483','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0647','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0647','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '04/552','Change this payment from BEFTN to Cheque issue.','dsamaddar'
exec spInsertClosedAgreements '03/4595-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/8181-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8181-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8181-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8181-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8181-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8181-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8181-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10848','Change this payment from BEFTN to Cheque issue.','dsamaddar'
exec spInsertClosedAgreements '01/10510','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10510','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10510','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10510','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6561','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6561','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6561','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6561','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6561','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6561','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6561','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6561','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6561','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6561','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6561','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6561','Under Loan','dsamaddar'
exec spInsertClosedAgreements '03/6617','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6617','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6617','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6617','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6617','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6617','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6617','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8178-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8178-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8178-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8178-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8178-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8178-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8178-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8178-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8178-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10893','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10893','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10893','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10893','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10893','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10893','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10893','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10893','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10893','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10874','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10874','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10874','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10874','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10874','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10874','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10874','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10874','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10874','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10878','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10878','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10878','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10878','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10878','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10878','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10878','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10878','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10878','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10918','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10918','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10918','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10918','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10918','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10918','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10918','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10918','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10918','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10919','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10919','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10919','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10919','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10919','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10919','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10919','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10919','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10919','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '04/560','BEFTN Amount  is Credit our REFL Account . So that the amount is paid by issuing cheque.','dsamaddar'
exec spInsertClosedAgreements '04/560','Change this payment from BEFTN to Cheque issue.','dsamaddar'
exec spInsertClosedAgreements '03/6677','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6677','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6677','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6677','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6677','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6677','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6677','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6677','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6677','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11028','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11028','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11028','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11028','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11028','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11028','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11028','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0734','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0734','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10655','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10655','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/10655','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8409-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8409-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8409-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8409-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8409-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8409-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8409-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8409-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8409-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8409-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11055','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11055','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11055','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11055','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11066','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11066','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11066','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11066','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11066','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11066','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11066','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11066','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11085','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11085','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11085','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11085','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11085','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11085','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11085','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11085','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11085','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11085','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11152','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11152','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11152','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11152','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11152','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11152','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11152','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11152','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11153','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11153','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11153','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11153','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11153','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11153','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11153','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11153','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6814','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6814','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6814','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6814','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6814','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6814','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6814','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6814','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11117','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11117','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11117','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11117','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11117','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11117','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11117','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6862','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6862','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6862','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6862','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6862','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6862','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6862','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6862','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6862','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11179','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11179','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11179','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11179','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11179','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11179','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11179','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/2617-R2','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/2617-R2','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/2617-R2','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/2617-R2','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/2617-R2','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/2617-R2','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/2617-R2','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/2617-R2','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/2617-R2','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/2617-R2','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/2617-R2','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8414-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8414-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8414-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8414-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8414-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8414-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8414-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8414-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8414-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6765','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6765','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6765','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6765','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6765','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6765','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6765','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6765','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6765','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6765','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/6765','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8671-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8671-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8671-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8671-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8671-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8671-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8671-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8671-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8671-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8671-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/8671-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5072-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5072-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5072-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5072-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5072-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5072-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5072-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5072-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5072-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5072-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11285','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11285','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11285','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11285','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11285','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11285','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11285','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11285','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11285','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5146-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5146-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0828','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0828','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0828','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0828','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0828','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0828','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0828','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0828','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '02/917-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '02/917-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '02/917-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '02/917-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '02/917-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '02/917-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5292-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5292-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5292-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5292-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5292-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5292-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5292-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11354','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11354','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11354','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11354','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11354','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11354','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11354','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11354','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7048','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7048','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7048','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7048','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7048','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7048','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7048','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7048','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7048','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7048','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7048','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7048','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0111-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0111-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0111-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/8803-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/8803-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/8803-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/8803-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/8803-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/8803-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0132-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0132-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0132-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0132-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0132-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0132-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0132-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0132-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0132-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7062','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7062','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7062','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7062','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7062','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7062','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7062','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7062','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/7062','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '02/458-R2','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '02/458-R2','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '02/458-R2','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0935','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0935','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0935','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0935','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0935','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0935','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0935','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0935','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '05/0935','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/9192-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/9192-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/9192-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/9192-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/9193-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/9193-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/9193-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/9193-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11597','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11597','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11597','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5289-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5289-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5289-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5289-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5289-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5289-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5289-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5289-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11633','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11633','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11633','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11633','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11633','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11633','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11633','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11633','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11633','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11641','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11641','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11641','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11641','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11641','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11641','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11641','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11641','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11641','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5482-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5482-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5482-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5482-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5482-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5482-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5482-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5482-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5482-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '03/5482-R','Pre-Encash','dsamaddar'
exec spInsertClosedAgreements '01/11741','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11741','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11741','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11741','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11741','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11741','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11741','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11741','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/11741','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5589-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5589-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5589-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5589-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5589-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5589-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5589-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5589-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/5589-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '04/397-R','Change this payment from BEFTN to Cheque issue.','dsamaddar'
exec spInsertClosedAgreements '01/5498-R3','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/5498-R3','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/5498-R3','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/4146-R4','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/4146-R4','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/4146-R4','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/6451-R1','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/6451-R1','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/6451-R1','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/6451-R1','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/6451-R1','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/6451-R1','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/6451-R1','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/6451-R1','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '01/6451-R1','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0238-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0238-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0238-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0238-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0238-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0238-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0238-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0238-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0238-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0238-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0238-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0239-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0239-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0239-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0239-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0239-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0239-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0239-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0239-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0239-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0239-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '05/0239-R','Pre Encash','dsamaddar'
exec spInsertClosedAgreements '03/3945-R1','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3945-R1','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3945-R1','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3945-R1','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3945-R1','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3945-R1','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3945-R1','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3945-R1','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3945-R1','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3945-R1','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3945-R1','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3945-R1','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6008-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6008-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6008-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6008-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6008-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6008-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6008-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6008-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6008-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6008-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6008-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6008-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3858-R2','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3858-R2','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3858-R2','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3858-R2','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3858-R2','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3858-R2','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3858-R2','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3858-R2','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3858-R2','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3858-R2','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3858-R2','Encash','dsamaddar'
exec spInsertClosedAgreements '03/3858-R2','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6054-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6054-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6054-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6054-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6054-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6054-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6054-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6054-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6054-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6054-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6054-R','Encash','dsamaddar'
exec spInsertClosedAgreements '03/6054-R','Encash','dsamaddar'
